version: '3'

services:

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
    container_name: app
    restart: always
    tty: true
    networks:
      - app-network
    volumes: 
      - ./node:/usr/src/app
      - node_modules:/usr/src/app/node_modules      
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    # image: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      # test: ["CMD", "mysqladmin ", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      # test: ["CMD", "mysqladmin", "-uroot", "-p$MYSQL_ROOT_PASSWORD", "ping", "-h", "localhost"]
      # test: ["CMD", "mysqladmin", "-uroot", "-proot",  "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:  
